library(MASS)
library(ggplot2)
library(dplyr)
library(tidyverse)
library(corrplot)
library(leaps)
library(olsrr)
library(rpart)
library(mgcv)
library(boot)
library(rpart)
library(rpart.plot)

df_diamonds <- read.csv('/Users/baccandres/Ironhack_Projects/DiamondPricingModel/data/DiamondsPricing.csv')

head(df_diamonds)
dim(df_diamonds)
str(df_diamonds)
summary(df_diamonds)
sum(duplicated((df_diamonds)))
